//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Final_year_project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_setExam
    {
        public int Exam_id { get; set; }
        public Nullable<System.DateTime> Exam_date { get; set; }
        public Nullable<int> Exam__fk_stu { get; set; }
        public string Exam_name { get; set; }
        public Nullable<int> std_score { get; set; }
    
        public virtual student student { get; set; }
    }
}
